
export const OTP_SENT = 'OTP_SENT';
export const OTP_SENT_ERROR = 'OTP_SENT_ERROR';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const OTP_INVALID = 'OTP_INVALID';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';


export const USER_LOGOUT = 'USER_LOGOUT';
export const LOAD_USER = 'LOAD_USER';

export const VERIFY_AUTH_REQUEST = 'VERIFY_AUTH_REQUEST';
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';

export const INIT_BLOCKCHAIN_REQUEST = 'INIT_BLOCKCHAIN_REQUEST';
export const INIT_BLOCKCHAIN_SUCCESS = 'INIT_BLOCKCHAIN_SUCCESS';
export const INIT_BLOCKCHAIN_FAIL = 'INIT_BLOCKCHAIN_FAIL';


export const GET_CANDIDATES_REQUEST = 'GET_CANDIDATES_REQUEST';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_FAILURE = 'GET_CANDIDATES_FAILURE';

export const ADD_CANDIDATES_REQUEST = 'ADD_CANDIDATES_REQUEST';
export const ADD_CANDIDATES_SUCCESS = 'ADD_CANDIDATES_SUCCESS';
export const ADD_CANDIDATES_FAILURE = 'ADD_CANDIDATES_FAILURE';


export const DELETE_CANDIDATES_REQUEST = 'DELETE_CANDIDATES_REQUEST';
export const DELETE_CANDIDATES_SUCCESS = 'DELETE_CANDIDATES_SUCCESS';
export const DELETE_CANDIDATES_FAILURE = 'DELETE_CANDIDATES_FAILURE';


export const VOTE_CANDIDATE_REQUEST = 'VOTE_CANDIDATE_REQUEST';
export const VOTE_CANDIDATE_FAILURE = 'VOTE_CANDIDATE_FAILURE';
export const VOTE_CANDIDATE_SUCCESS = 'VOTE_CANDIDATE_SUCCESS';

export const ELECTION_PHASE_CHANGE_REQUEST = 'ELECTION_PHASE_CHANGE_REQUEST';
export const ELECTION_PHASE_CHANGE_SUCCESS = 'ELECTION_PHASE_CHANGE_SUCCESS';
export const ELECTION_PHASE_CHANGE_FAILURE = 'ELECTION_PHASE_CHANGE_FAILURE';


export const SET_ACCOUNT = 'SET_ACCOUNT';

export const INIT_ELECTION_CONTRACT = 'INIT_ELECTION_CONTRACT';
export const INIT_ELECTION_CONTRACT_LOADING = 'INIT_ELECTION_CONTRACT_LOADING';

export const GET_ELECTION_PHASE_REQUEST = 'GET_ELECTION_PHASE_REQUEST';
export const GET_ELECTION_PHASE_SUCCESS = 'GET_ELECTION_PHASE_SUCCESS';
export const GET_ELECTION_PHASE_FAILURE = 'GET_ELECTION_PHASE_FAILURE';

