
export const OTP_SENT = 'OTP_SENT';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const OTP_INVALID = 'OTP_INVALID';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';


export const USER_LOGOUT = 'USER_LOGOUT';
export const LOAD_USER = 'LOAD_USER';

export const VERIFY_AUTH_REQUEST = 'VERIFY_AUTH_REQUEST';
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
